# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quote', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[(b'None', b'None'), (b'Happy', b'Happy'), (b'Sad', b'Sad'), (b'Inspiring', b'Inspiring'), (b'Romantic', b'Romantic'), (b'Sarcastic', b'Sarcastic'), (b'Funny', b'Funny'), (b'Evil', b'Evil'), (b'Bravery', b'Bravery'), (b'Wisdom', b'Wisdom')], default='Happy', max_length=100)),
            ],
        ),
    ]
